#!/usr/bin/env bash
set -euo pipefail

# Summarize secure-ring permission (ACL) overhead collected from cxl_ring_direct.
#
# Input artifact generated by host_recreate_and_bench_tdx.sh when OVERHEAD_STATS=1:
#   results/secure_perm_<TS>.json
#
# Usage:
#   bash scripts/summarize_secure_perm_overhead.sh --ts 20260131_232552
#   bash scripts/summarize_secure_perm_overhead.sh --ts 20260131_232552 --amortize-ops 200000
#   # If --ts is omitted, the latest results/secure_perm_*.json is used.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTDIR="${ROOT}/results"

TS=""
AMORTIZE_OPS=""

usage() {
  echo "Usage: $0 [--ts TS] [--amortize-ops N]" >&2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ts) TS="$2"; shift 2 ;;
    --amortize-ops) AMORTIZE_OPS="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "${TS}" ]]; then
  latest=$(ls -1t "${OUTDIR}"/secure_perm_*.json 2>/dev/null | head -n1 || true)
  if [[ -z "${latest}" ]]; then
    echo "[!] No secure_perm_*.json found under ${OUTDIR}" >&2
    exit 1
  fi
  base=$(basename "${latest}")
  TS="${base#secure_perm_}"
  TS="${TS%.json}"
fi

json="${OUTDIR}/secure_perm_${TS}.json"
if [[ ! -f "${json}" ]]; then
  echo "[!] Missing artifact: ${json}" >&2
  exit 1
fi

extract_json_field() {
  local file="$1" key="$2"
  sed -n "s/.*\"${key}\"[: ]*\"\\{0,1\\}\\([0-9A-Za-z._-]*\\)\"\\{0,1\\}.*/\\1/p" "${file}" | head -n1
}

mode=$(extract_json_field "${json}" mode)
node_id=$(extract_json_field "${json}" node_id)
ring_count=$(extract_json_field "${json}" ring_count)
table_wait_ns=$(extract_json_field "${json}" table_wait_ns); : "${table_wait_ns:=0}"
principal_sleep_ns=$(extract_json_field "${json}" principal_sleep_ns); : "${principal_sleep_ns:=0}"
sec_mgr_calls=$(extract_json_field "${json}" sec_mgr_calls); : "${sec_mgr_calls:=0}"
sec_mgr_ns=$(extract_json_field "${json}" sec_mgr_ns); : "${sec_mgr_ns:=0}"
perm_total_ns=$(extract_json_field "${json}" perm_total_ns); : "${perm_total_ns:=0}"

ns_to_ms() { awk -v x="$1" 'BEGIN{printf "%.3f", x/1e6}' ; }
ns_to_us() { awk -v x="$1" 'BEGIN{printf "%.2f", x/1e3}' ; }

echo "[secure permission overhead] TS=${TS} mode=${mode} node_id=${node_id} ring_count=${ring_count}"
echo "- table wait:      $(ns_to_ms "${table_wait_ns}") ms"
echo "- principal sleep: $(ns_to_ms "${principal_sleep_ns}") ms"
echo "- sec_mgr calls:   ${sec_mgr_calls} calls, $(ns_to_ms "${sec_mgr_ns}") ms"
echo "- total:           $(ns_to_ms "${perm_total_ns}") ms"

if [[ -n "${AMORTIZE_OPS}" ]]; then
  if [[ "${AMORTIZE_OPS}" -le 0 ]]; then
    echo "[!] --amortize-ops must be > 0" >&2
    exit 1
  fi
  echo "- amortized:       $(awk -v x="${perm_total_ns}" -v n="${AMORTIZE_OPS}" 'BEGIN{printf "%.2f", (x/1000.0)/n}') us/op"
fi

